### ISSUE TITLE
where I can download blast formal analysis data

### ISSUE THREAD

**Issue by CaiWang0503** [richardmleggett/MARTi#5]
Hi,
MARTi is very useful, I have been trying for some of my data. Now I would like to output identification with taxonomic path, I watched a video that Richard talked about there is an option to output blast formal data to put in magan, however I can't find where I can do it in Marti_gui, could anyone help with it?
Thank you very much

**Comment by richardmleggett** [comment]
Hi there! Thanks for your query.

Do you mean:
1.  You want to output each read and a taxonomic path for each read?
2. You want to output a taxonomic path and then the count of reads for each taxonomic path?
3. Or something else?

If 1, within each project directory, there is an lcaparse subdirectory. Inside there, you will find a set of files ending in _perread.txt which contains every classified read ID and the NCBI taxonomy ID they have been assigned to. See https://marti.readthedocs.io/en/latest/downstream.html for description of the fields.

If 2, you can use the Export Data option in the GUI Samples page.

You asked about MEGAN exports. The support for this needs to be improved, but there is some partial support for generating MEGAN files which you can read about at https://marti.readthedocs.io/en/latest/downstream.html . But the easiest thing might be to use the Export Data option described above to export a tab separated file which you can import into MEGAN.

Feel free to email me (just google "Richard Leggett Earlham Institute") if you want to discuss further, or you have ideas for improving output.
